/*
AUTOGENERATED
*/

import { InferService, ServiceContainer, WorkerContainer, QueueContainer } from "@csi-foxbyte/fastify-toab";

import configService from "../config/config.service.js";
import authService from "../auth/auth.service.js";
import databaseService from "../database/database.service.js";

export type ConfigService = InferService<typeof configService>;
export type AuthService = InferService<typeof authService>;
export type DatabaseService = InferService<typeof databaseService>;

export function getConfigService(deps: ServiceContainer) {
    return deps.get<ConfigService>(configService.name);
}
export function getAuthService(deps: ServiceContainer) {
    return deps.get<AuthService>(authService.name);
}
export function getDatabaseService(deps: ServiceContainer) {
    return deps.get<DatabaseService>(databaseService.name);
}

