/*
AUTOGENERATED
*/

import { InferService, ServiceContainer, WorkerContainer, QueueContainer } from "@csi-foxbyte/fastify-toab";

import authService from "../auth/auth.service.js";
import configService from "../config/config.service.js";
import databaseService from "../database/database.service.js";
import submissionsService from "../submissions/submissions.service.js";

export type AuthService = InferService<typeof authService>;
export type ConfigService = InferService<typeof configService>;
export type DatabaseService = InferService<typeof databaseService>;
export type SubmissionsService = InferService<typeof submissionsService>;

export function getAuthService(deps: ServiceContainer) {
    return deps.get<AuthService>(authService.name);
}
export function getConfigService(deps: ServiceContainer) {
    return deps.get<ConfigService>(configService.name);
}
export function getDatabaseService(deps: ServiceContainer) {
    return deps.get<DatabaseService>(databaseService.name);
}
export function getSubmissionsService(deps: ServiceContainer) {
    return deps.get<SubmissionsService>(submissionsService.name);
}

