/*
AUTOGENERATED!
*/

import {
  ControllerRegistry,
  ServiceRegistry,
  WorkerRegistry,
} from "@csi-foxbyte/fastify-toab";
import auth_auth$service from "../auth/auth.service.js";
import config_config$service from "../config/config.service.js";
import database_database$service from "../database/database.service.js";
import feedback_feedback$service from "../feedback/feedback.service.js";
import submissions_submissions$service from "../submissions/submissions.service.js";
import auth_auth$controller from "../auth/auth.controller.js";
import config_config$controller from "../config/config.controller.js";
import feedbackAdmin_feedbackAdmin$controller from "../feedbackAdmin/feedbackAdmin.controller.js";
import feedbackPublic_feedbackPublic$controller from "../feedbackPublic/feedbackPublic.controller.js";
import submissionsAdmin_submissionsAdmin$controller from "../submissionsAdmin/submissionsAdmin.controller.js";
import submissionsPublic_submissionsPublic$controller from "../submissionsPublic/submissionsPublic.controller.js";
import terrain_terrain$controller from "../terrain/terrain.controller.js";
import test_test$controller from "../test/test.controller.js";
import tiles_tiles$controller from "../tiles/tiles.controller.js";

let serviceRegistry: ServiceRegistry | null = null;
let workerRegistry: WorkerRegistry | null = null;
let controllerRegistry: ControllerRegistry | null = null;

export async function getRegistries(dontInitializeWorkers?: boolean) {
  if (serviceRegistry !== null && workerRegistry !== null && controllerRegistry !== null) return { controllerRegistry, serviceRegistry, workerRegistry };

  let workerRegistryRef: { current: WorkerRegistry | null } = {
    current: null,
  };

  serviceRegistry = new ServiceRegistry(workerRegistryRef);
  serviceRegistry.register(auth_auth$service);
  serviceRegistry.register(config_config$service);
  serviceRegistry.register(database_database$service);
  serviceRegistry.register(feedback_feedback$service);
  serviceRegistry.register(submissions_submissions$service);

  workerRegistry = new WorkerRegistry(serviceRegistry);
  if (!dontInitializeWorkers) {

  };

  workerRegistryRef.current = workerRegistry;

  await workerRegistry.resumeQueues();

  controllerRegistry = new ControllerRegistry(serviceRegistry);
  controllerRegistry.register(auth_auth$controller);
  controllerRegistry.register(config_config$controller);
  controllerRegistry.register(feedbackAdmin_feedbackAdmin$controller);
  controllerRegistry.register(feedbackPublic_feedbackPublic$controller);
  controllerRegistry.register(submissionsAdmin_submissionsAdmin$controller);
  controllerRegistry.register(submissionsPublic_submissionsPublic$controller);
  controllerRegistry.register(terrain_terrain$controller);
  controllerRegistry.register(test_test$controller);
  controllerRegistry.register(tiles_tiles$controller);

  return { controllerRegistry, serviceRegistry, workerRegistry };
}

/**
 * Use this function inside a sandboxedWorker to gain access to services and other workers.
 */
export async function initializeContainers() {
  const { serviceRegistry, workerRegistry } = await getRegistries(true);

  return {
    services: serviceRegistry.resolve(),
    queues: { get: workerRegistry.getQueue.bind(workerRegistry) },
  };
}
