//////////////////////////////////////////////////////////////////////////////////////////////
// DO NOT MODIFY THIS FILE                                                                  //
// This file is automatically generated by ZenStack CLI and should not be manually updated. //
//////////////////////////////////////////////////////////////////////////////////////////////

/* eslint-disable */

import { type SchemaType as $Schema } from "./schema.js";
import type { FindManyArgs as $FindManyArgs, FindUniqueArgs as $FindUniqueArgs, FindFirstArgs as $FindFirstArgs, ExistsArgs as $ExistsArgs, CreateArgs as $CreateArgs, CreateManyArgs as $CreateManyArgs, CreateManyAndReturnArgs as $CreateManyAndReturnArgs, UpdateArgs as $UpdateArgs, UpdateManyArgs as $UpdateManyArgs, UpdateManyAndReturnArgs as $UpdateManyAndReturnArgs, UpsertArgs as $UpsertArgs, DeleteArgs as $DeleteArgs, DeleteManyArgs as $DeleteManyArgs, CountArgs as $CountArgs, AggregateArgs as $AggregateArgs, GroupByArgs as $GroupByArgs, WhereInput as $WhereInput, SelectInput as $SelectInput, IncludeInput as $IncludeInput, OmitInput as $OmitInput, QueryOptions as $QueryOptions } from "@zenstackhq/orm";
import type { SimplifiedPlainResult as $Result, SelectIncludeOmit as $SelectIncludeOmit } from "@zenstackhq/orm";
export type UserFindManyArgs = $FindManyArgs<$Schema, "User">;
export type UserFindUniqueArgs = $FindUniqueArgs<$Schema, "User">;
export type UserFindFirstArgs = $FindFirstArgs<$Schema, "User">;
export type UserExistsArgs = $ExistsArgs<$Schema, "User">;
export type UserCreateArgs = $CreateArgs<$Schema, "User">;
export type UserCreateManyArgs = $CreateManyArgs<$Schema, "User">;
export type UserCreateManyAndReturnArgs = $CreateManyAndReturnArgs<$Schema, "User">;
export type UserUpdateArgs = $UpdateArgs<$Schema, "User">;
export type UserUpdateManyArgs = $UpdateManyArgs<$Schema, "User">;
export type UserUpdateManyAndReturnArgs = $UpdateManyAndReturnArgs<$Schema, "User">;
export type UserUpsertArgs = $UpsertArgs<$Schema, "User">;
export type UserDeleteArgs = $DeleteArgs<$Schema, "User">;
export type UserDeleteManyArgs = $DeleteManyArgs<$Schema, "User">;
export type UserCountArgs = $CountArgs<$Schema, "User">;
export type UserAggregateArgs = $AggregateArgs<$Schema, "User">;
export type UserGroupByArgs = $GroupByArgs<$Schema, "User">;
export type UserWhereInput = $WhereInput<$Schema, "User">;
export type UserSelect = $SelectInput<$Schema, "User">;
export type UserInclude = $IncludeInput<$Schema, "User">;
export type UserOmit = $OmitInput<$Schema, "User">;
export type UserGetPayload<Args extends $SelectIncludeOmit<$Schema, "User", true>, Options extends $QueryOptions<$Schema> = $QueryOptions<$Schema>> = $Result<$Schema, "User", Args, Options>;
export type ConfigFindManyArgs = $FindManyArgs<$Schema, "Config">;
export type ConfigFindUniqueArgs = $FindUniqueArgs<$Schema, "Config">;
export type ConfigFindFirstArgs = $FindFirstArgs<$Schema, "Config">;
export type ConfigExistsArgs = $ExistsArgs<$Schema, "Config">;
export type ConfigCreateArgs = $CreateArgs<$Schema, "Config">;
export type ConfigCreateManyArgs = $CreateManyArgs<$Schema, "Config">;
export type ConfigCreateManyAndReturnArgs = $CreateManyAndReturnArgs<$Schema, "Config">;
export type ConfigUpdateArgs = $UpdateArgs<$Schema, "Config">;
export type ConfigUpdateManyArgs = $UpdateManyArgs<$Schema, "Config">;
export type ConfigUpdateManyAndReturnArgs = $UpdateManyAndReturnArgs<$Schema, "Config">;
export type ConfigUpsertArgs = $UpsertArgs<$Schema, "Config">;
export type ConfigDeleteArgs = $DeleteArgs<$Schema, "Config">;
export type ConfigDeleteManyArgs = $DeleteManyArgs<$Schema, "Config">;
export type ConfigCountArgs = $CountArgs<$Schema, "Config">;
export type ConfigAggregateArgs = $AggregateArgs<$Schema, "Config">;
export type ConfigGroupByArgs = $GroupByArgs<$Schema, "Config">;
export type ConfigWhereInput = $WhereInput<$Schema, "Config">;
export type ConfigSelect = $SelectInput<$Schema, "Config">;
export type ConfigInclude = $IncludeInput<$Schema, "Config">;
export type ConfigOmit = $OmitInput<$Schema, "Config">;
export type ConfigGetPayload<Args extends $SelectIncludeOmit<$Schema, "Config", true>, Options extends $QueryOptions<$Schema> = $QueryOptions<$Schema>> = $Result<$Schema, "Config", Args, Options>;
