version: "3.9"
name: rg-dez-backend
services:
  dev:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspace
    command: sleep infinity
    ports:
      - 5000:5000
    environment:
      NODE_ENV: development

  redis:
    image: redis
    restart: on-failure
    ports:
      - 6379:6379
