/*
AUTOGENERATED!
*/

import {
  ControllerRegistry,
  ServiceRegistry,
  WorkerRegistry,
} from "@csi-foxbyte/fastify-toab";
import auth_auth$service from "./auth/auth.service.js";
import admin_admin$controller from "./admin/admin.controller.js";
import auth_auth$controller from "./auth/auth.controller.js";

let serviceRegistry: ServiceRegistry | null = null;
let workerRegistry: WorkerRegistry | null = null;
let controllerRegistry: ControllerRegistry | null = null;

export async function getRegistries(dontInitializeWorkers?: boolean) {
  if (serviceRegistry !== null && workerRegistry !== null && controllerRegistry !== null) return { controllerRegistry, serviceRegistry, workerRegistry };

  let workerRegistryRef: { current: WorkerRegistry | null } = {
    current: null,
  };

  serviceRegistry = new ServiceRegistry(workerRegistryRef);
  serviceRegistry.register(auth_auth$service);

  workerRegistry = new WorkerRegistry(serviceRegistry);

  workerRegistryRef.current = workerRegistry;

  await workerRegistry.resumeQueues();

  controllerRegistry = new ControllerRegistry(serviceRegistry);
  controllerRegistry.register(admin_admin$controller);
  controllerRegistry.register(auth_auth$controller);

  return { controllerRegistry, serviceRegistry, workerRegistry };
}

/**
 * Use this function inside a sandboxedWorker to gain access to services and other workers.
 */
export async function initializeContainers() {
  const { serviceRegistry, workerRegistry } = await getRegistries(true);

  return {
    services: serviceRegistry.resolve(),
    queues: { get: workerRegistry.getQueue.bind(workerRegistry) },
  };
}
